coverage:
  status:
    project:
      default:
        enabled: yes
        target: 52%  # TODO: Adjust this target based on your project's requirements and coverage progress
    patch:
      default:
        enabled: yes
        target: 55%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false